const main = async () => {
    console.log("Done");
};

main().catch((error) => {
    console.error(error);
    process.exit(1);
});
